# -*- coding: utf-8 -*-
"""enhanced cascade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11P05iOfQ6w73sn56ZlOKMkXNfgEmxdOJ
"""

import pandas as pd
from transformers import pipeline
import nltk
from nltk.tokenize import sent_tokenize
from tqdm.auto import tqdm

# 1. Download the NLTK sentence splitter logic
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

# 2. Load Your Dataset
INPUT_CSV = "full_dataset_with_predictions.csv"
OUTPUT_CSV = "enhanced_cascade_results.csv"

df = pd.read_csv(INPUT_CSV)
print(f"Loaded {len(df)} reviews from {INPUT_CSV}.")

# 3. Initialize the Enhanced Classifier
print("Loading Enhanced Sentiment Model...")
# Using DistilBERT for speed. Change device=0 if you have a GPU enabled in Colab!
enhanced_model = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english", device=-1)

# ---------------------------------------------------------
# STAGE 1: The Router (Suspicion Logic Gate)
# ---------------------------------------------------------
def is_suspicious(base_polarity, stars):
    """
    Flags the review if the text sentiment heavily contradicts the star rating.
    """
    if pd.isna(stars) or pd.isna(base_polarity):
        return False

    # Base says Negative, but user gave 4 or 5 stars (Hidden Gem / Sarcastic Praise / Enthusiastic Rant)
    if base_polarity == -1 and stars >= 4: return True
    # Base says Positive, but user gave 1 or 2 stars (Polite Intro / Sarcastic Complaint)
    if base_polarity == 1 and stars <= 2: return True

    return False

# ---------------------------------------------------------
# STAGE 2: The Enhanced Classifier (Chunking & Weighting)
# ---------------------------------------------------------
def enhanced_deep_analysis(text):
    """
    Splits long raw text into sentences. Analyzes each separately.
    Applies heavy mathematical weight to the END of the review to catch pivots.
    """
    sentences = sent_tokenize(str(text))
    if not sentences:
        return 0 # Neutral fallback

    total_score = 0
    num_sentences = len(sentences)
    pivot_words = ['but', 'however', 'although', 'in the end', 'sadly', 'disappointed']

    for i, sentence in enumerate(sentences):
        short_sent = sentence[:512]
        res = enhanced_model(short_sent)[0]
        chunk_score = 1 if res['label'] == 'POSITIVE' else -1

        weight = 1.0

        # Rule A: The Recency Bias (The last 30% of a review matters most)
        if i >= num_sentences * 0.7:
            weight += 1.5

        # Rule B: The Pivot Multiplier (Did they say "BUT" or "HOWEVER"?)
        sentence_lower = sentence.lower()
        if any(pivot in sentence_lower for pivot in pivot_words):
            weight += 2.0

        total_score += (chunk_score * weight)

    return 1 if total_score > 0 else -1

# ---------------------------------------------------------
# STAGE 3: The Main Execution Loop
# ---------------------------------------------------------
new_final_polarities = []
routed_to = []
flagged_count = 0

print("Routing data and applying deep analysis where needed...")
progress_bar = tqdm(total=len(df), desc="Processing Pipeline")

for index, row in df.iterrows():
    raw_text = row['review_text']
    stars = row['star_rating']
    # Grabbing your specific column name from the new dataset
    base_pol = row['pred_polarity']

    # Route it
    if is_suspicious(base_pol, stars):
        flagged_count += 1
        routed_to.append("Enhanced Model")

        # Apply Deep Analysis only to the suspicious rows
        new_pol = enhanced_deep_analysis(raw_text)
        new_final_polarities.append(new_pol)
    else:
        # Safe! Keep the original base sentiment.
        routed_to.append("Base Model")
        new_final_polarities.append(base_pol)

    progress_bar.update(1)

progress_bar.close()

# ---------------------------------------------------------
# STAGE 4: Save and Evaluate
# ---------------------------------------------------------
df['routing_path'] = routed_to
df['enhanced_final_polarity'] = new_final_polarities
df.to_csv(OUTPUT_CSV, index=False)
print(f"\n--- PIPELINE SUMMARY ---")
print(f"Total Reviews Processed: {len(df)}")
print(f"Reviews safely handled by Base Model: {len(df) - flagged_count}")
print(f"Suspicious Reviews routed to Enhanced Model: {flagged_count}")
print(f"Saved refined dataset to: {OUTPUT_CSV}")

from google.colab import files
files.download("enhanced_cascade_results.csv")



from google.colab import files

# This will open a file picker dialog
files.upload()