# -*- coding: utf-8 -*-
"""twitter-roberta-base-irony.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_001fk98DvIEMYXQY0Rf_GJ5Fz4WBe5
"""

# 1. Install required libraries (Colab already has PyTorch installed!)
!pip install transformers tqdm -q

import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm.auto import tqdm

# ------------------------------
# 2. Load Your EXISTING Data
# ------------------------------
INPUT_CSV = "full_dataset_with_predictions.csv"
OUTPUT_CSV = "final_dataset_with_sarcasm_merged.csv"

# Load the file you just uploaded
df = pd.read_csv(INPUT_CSV)

# Verify we have the columns we need (removed the polarity check)
if "cleaned_review" not in df.columns:
    raise ValueError("CSV must contain a `cleaned_review` column.")

texts = df["cleaned_review"].fillna("").astype(str).tolist()
n = len(texts)
print(f"Loaded {n} reviews for sarcasm detection.")

# ------------------------------
# 3. Load ONLY the Sarcasm Model
# ------------------------------
SARC_MODEL_NAME = "cardiffnlp/twitter-roberta-base-irony"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

sarc_tokenizer = AutoTokenizer.from_pretrained(SARC_MODEL_NAME)
sarc_model = AutoModelForSequenceClassification.from_pretrained(SARC_MODEL_NAME)
sarc_model.to(device)
sarc_model.eval()

# ------------------------------
# 4. Batched Inference
# ------------------------------
batch_size = 32
max_length = 128

# SET YOUR THRESHOLD HERE
SARCASM_THRESHOLD = 0.6

# Using a simpler list extension method instead of pre-allocating
pred_sarcasm = []

with torch.no_grad():
    progress_bar = tqdm(range(0, n, batch_size), desc="Detecting Sarcasm", unit="batch")

    for start_idx in progress_bar:
        end_idx = min(n, start_idx + batch_size)
        batch_texts = texts[start_idx:end_idx]

        # --- Sarcasm Inference ---
        enc_sarc = sarc_tokenizer(batch_texts, padding=True, truncation=True, max_length=max_length, return_tensors="pt")
        enc_sarc = {k: v.to(device) for k, v in enc_sarc.items()}

        # Get raw scores (logits)
        sarc_logits = sarc_model(**enc_sarc).logits

        # Convert logits to percentages using Softmax
        probs = torch.softmax(sarc_logits, dim=-1)

        # Extract the probability that the text is sarcastic (Class 1)
        sarcastic_probs = probs[:, 1]

        # Flag as 1 ONLY if the probability meets the threshold
        sarc_preds = (sarcastic_probs >= SARCASM_THRESHOLD).int().tolist()

        # Add the batch results to our master list
        pred_sarcasm.extend(sarc_preds)

# ------------------------------
# 5. Save Results
# ------------------------------
# Just add the new sarcasm column, leaving everything else untouched
df["pred_sarcasm"] = pred_sarcasm

df.to_csv(OUTPUT_CSV, index=False)
print("Saved:", OUTPUT_CSV)

# --- Quick stats for your IR Project Report ---
print("\n--- Model Output Stats ---")
print(f"Total Sarcastic Reviews Found (Threshold > {SARCASM_THRESHOLD}): {sum(pred_sarcasm)}")

from google.colab import files

# This will open a file picker dialog
files.upload()

from google.colab import files
files.download("final_dataset_with_sarcasm_merged.csv")

